export const BUSINESS_LOCATIONS = [
  'Andorra la Vella',
  'Escaldes-Engordany',
  'Encamp',
  'La Massana',
  'Ordino',
  'Canillo',
  'Soldeu',
  'El Tarter',
  'Pas de la Casa',
  'Sant Julià de Lòria',
  'Arinsal',
] as const;

/** Las 7 parroquias oficiales de Andorra. */
export const ANDORRA_PARISHES = [
  'Andorra la Vella',
  'Escaldes-Engordany',
  'Encamp',
  'La Massana',
  'Ordino',
  'Canillo',
  'Sant Julià de Lòria',
] as const;

export type AndorraParish = (typeof ANDORRA_PARISHES)[number];

const LOCATION_PARISH_MAP: Record<string, AndorraParish> = {
  'Pas de la Casa': 'Encamp',
  Soldeu: 'Canillo',
  'El Tarter': 'Canillo',
  Arinsal: 'La Massana',
};

export function getParishForLocation(location: string): AndorraParish | null {
  if ((ANDORRA_PARISHES as readonly string[]).includes(location)) {
    return location as AndorraParish;
  }
  return LOCATION_PARISH_MAP[location] ?? null;
}

export const PARISH_MAP_CENTERS: Record<AndorraParish, [number, number]> = {
  'Andorra la Vella': [42.5063, 1.5218],
  'Escaldes-Engordany': [42.5085, 1.54],
  Encamp: [42.536, 1.582],
  'La Massana': [42.545, 1.514],
  Ordino: [42.556, 1.533],
  Canillo: [42.567, 1.598],
  'Sant Julià de Lòria': [42.463, 1.491],
};

export type BusinessServiceGroup = {
  id: string;
  label: string;
  services: readonly string[];
};

export const BUSINESS_SERVICE_GROUPS: readonly BusinessServiceGroup[] = [
  {
    id: 'comodidades',
    label: 'Comodidades',
    services: [
      'Wifi',
      'Wifi de alta velocidad',
      'Aire acondicionado',
      'Calefacción',
      'Zona de trabajo',
      'Enchufes USB',
      'Taquillas',
      'Consigna equipaje',
      'Guardarropa',
      'Toallas incluidas',
      'Productos de baño',
      'Secador de pelo',
      'Plan cha',
      'Habitaciones insonorizadas',
    ],
  },
  {
    id: 'acceso',
    label: 'Acceso y parking',
    services: [
      'Parking',
      'Parking gratuito',
      'Parking cubierto',
      'Parking vigilado',
      'Accesible',
      'Acceso sin escaleras',
      'Ascensor',
      'Rampa de acceso',
      'Baño adaptado',
      'Entrada autónoma',
      'Recepción 24 h',
    ],
  },
  {
    id: 'gastronomia',
    label: 'Gastronomía',
    services: [
      'Restaurante',
      'Bar',
      'Cafetería',
      'Menú del día',
      'Menú degustación',
      'Carta vegana',
      'Opciones vegetarianas',
      'Sin gluten',
      'Sin lactosa',
      'Cocina local',
      'Producto de proximidad',
      'Brunch',
      'Desayuno',
      'Desayuno buffet',
      'Comida para llevar',
      'Delivery',
      'Terraza',
      'Zona de comedor exterior',
      'Bodega',
      'Maridaje de vinos',
      'Catas',
      'Cocina abierta',
      'Chef privado',
    ],
  },
  {
    id: 'alojamiento',
    label: 'Alojamiento',
    services: [
      'Desayuno incluido',
      'Media pensión',
      'Pensión completa',
      'Servicio de habitaciones',
      'Limpieza diaria',
      'Cambio de sábanas',
      'Minibar',
      'Caja fuerte',
      'Cuna disponible',
      'Cama supletoria',
      'Suite disponible',
      'Apartamento equipado',
      'Cocina compartida',
      'Lavandería',
      'Lavandería autoservicio',
      'Traslado al aeropuerto',
      'Servicio de conserjería',
    ],
  },
  {
    id: 'bienestar',
    label: 'Bienestar y spa',
    services: [
      'Spa',
      'Sauna',
      'Masajes',
      'Jacuzzi',
      'Bañera de hidromasaje',
      'Hamam',
      'Baño turco',
      'Piscina',
      'Piscina climatizada',
      'Piscina exterior',
      'Gimnasio',
      'Clases de yoga',
      'Clases de pilates',
      'Tratamientos faciales',
      'Circuito termal',
      'Zona de relax',
      'Vestuarios',
    ],
  },
  {
    id: 'montana',
    label: 'Montaña y deporte',
    services: [
      'Ski-in',
      'Ski-out',
      'Alquiler de esquí',
      'Alquiler de snowboard',
      'Guardaesquís',
      'Tienda de material',
      'Escuela de esquí',
      'Clases privadas',
      'Rutas de senderismo',
      'Rutas BTT',
      'Raquetas de nieve',
      'Trineos',
      'Escalada',
      'Pádel',
      'Tenis',
      'Golf cercano',
      'Alquiler de bicicletas',
      'Almacén de bicicletas',
    ],
  },
  {
    id: 'familia',
    label: 'Familia y mascotas',
    services: [
      'Niños',
      'Zona infantil',
      'Menú infantil',
      'Cunas',
      'Sillas altas',
      'Actividades para niños',
      'Campamento infantil',
      'Pet-friendly',
      'Mascotas pequeñas',
      'Cuencos y camas para mascotas',
      'Paseo de perros',
    ],
  },
  {
    id: 'reservas',
    label: 'Reservas y pagos',
    services: [
      'Reservas online',
      'Reserva por teléfono',
      'Reserva por WhatsApp',
      'Pago con tarjeta',
      'Pago móvil',
      'Bizum',
      'Apple Pay / Google Pay',
      'Factura para empresa',
      'Bonos regalo',
      'Cancelación flexible',
    ],
  },
  {
    id: 'eventos',
    label: 'Eventos y grupos',
    services: [
      'Eventos',
      'Celebraciones privadas',
      'Bodas',
      'Comuniones',
      'Cumpleaños',
      'Eventos corporativos',
      'Team building',
      'Grupos escolares',
      'Salas para reuniones',
      'Proyector y pantalla',
      'Catering para eventos',
      'Coctelería para eventos',
    ],
  },
  {
    id: 'compras',
    label: 'Compras y retail',
    services: [
      'Tienda',
      'Recogida en tienda',
      'Envío a domicilio',
      'Envío internacional',
      'Cambios y devoluciones',
      'Asesoramiento personalizado',
      'Personal shopper',
      'Duty free',
      'Artesanía local',
      'Souvenirs',
    ],
  },
  {
    id: 'experiencias',
    label: 'Experiencias y turismo',
    services: [
      'Visitas guiadas',
      'Excursiones organizadas',
      'Alquiler de vehículos',
      'Taxi concertado',
      'Información turística',
      'Mapas y rutas',
      'Alquiler de GPS',
      'Espectáculos',
      'Música en vivo',
      'Karaoke',
      'Escape room',
      'Bowling',
      'Cine',
      'Museo o exposición',
    ],
  },
  {
    id: 'servicios',
    label: 'Atención y servicios',
    services: [
      'Atención en catalán',
      'Atención en castellano',
      'Atención en francés',
      'Atención en inglés',
      'Servicio 24 h',
      'Cita previa',
      'Urgencias',
      'A domicilio',
      'Presupuesto sin compromiso',
      'Garantía',
      'Soporte postventa',
      'Programa de fidelización',
    ],
  },
] as const;

/** Lista plana de todos los servicios (sin duplicados). */
export const BUSINESS_SERVICES_OPTIONS: readonly string[] = [
  ...new Set(BUSINESS_SERVICE_GROUPS.flatMap(group => group.services)),
];
